import player from './player.ts';

export const PLAYERS: player[] = [
    {
        id: 1,
        name: "Arkhez",
        pseudo: "TrasbosEnString",
        tag: "SLIP",
        idLol: "5GN8xTHsa6KUOiOfp7_AQiy91lnDkoWC_2ifVrZMrNi2tJyqOKKAExoU8A",
        team: "KingKong",
        twitch: "https://www.twitch.tv/arkheztv",
    },
    {
        id: 2,
        name: "Mariuto",
        pseudo: "Maroui",
        tag: "2206",
        idLol: "SXgh7CU0nq_xAOBLQmzg-vzGaRMVB5qgNJJTK-jNZ4CnjFGWHUpxiB2JSQ",
        team : "Satoru Gojo",
        twitch: "",
    },
    {
        id: 3,
        name: "Viat",
        pseudo: "RIENATEGRAbdh",
        tag: "2433",
        idLol: "BPctBmtILojyZhrug7d32wTHrMKY7t1kVNzxIU7B6GdBB6-46JKsjzz9XA",
        team: "Team 1",
        twitch: "https://www.twitch.tv/viattv",
    },
    {
        id: 4,
        name: "Raiden",
        pseudo: "Jeong Ji hoon",
        tag: "정지훈",
        idLol: "2ZbU229Baj9WaWPSIhzXksTzZkMXsMYHNcV4x_2YkmlCiCLbM3FzK668fg",
        team: "Satoru Gojo",
        twitch: "https://www.twitch.tv/weezer___",
    },
    {
        id: 5,
        name: "Slash",
        pseudo: "Haklaynanno",
        tag: "6035",
        idLol: "23DgXUZX37oIngx-FpQTyqg4EzkfVoIpEd1N0IVPFpLFaQsQ7qYM0c2QBg",
        team: "Team 1",
        twitch: "",
    },
    {
        id: 6,
        name: "Rubix",
        pseudo: "NanikaHaruka",
        tag: "1234",
        idLol: "2qEJaTDEiYTBEmS4iw83P6XMdPSkmDMh_-1QfkA-yZHvKE_EfL4rb44bdw",
        team: "KingKong",
        twitch: "",
    },
    {
        id: 7,
        name: "Mastos",
        pseudo: "MALTY 2BZ",
        tag: "NCNC",
        idLol: "23DgXUZX37oIngx-FpQTyqg4EzkfVoIpEd1N0IVPFpLFaQsQ7qYM0c2QBg",
        team: "Don D. Gaetan",
        twitch: "https://www.twitch.tv/flyknit_",
    },
    {
        id: 8,
        name: "Axel",
        pseudo: "La4emeWave",
        tag: "2004",
        idLol: "ti6jwSbReBV7bJ8TwxbFUNftoqMv5LF_3gBa-vKSTKHp8p-z9YiUFGhRYQ",
        team: "Don D. Gaetan",
        twitch: "",
    },
    {
        id: 10,
        name: "Arkhez",
        pseudo: "Arkhez",
        tag: "EUW",
        idLol: "_r2HlqOEa5O447YmFlApvgITg5tsf-oL8qwSCnVdxCusdPg",
        team: "Team 3",
        twitch: "https://www.twitch.tv/arkheztv",
    },
    {
        id: 11,
        name: "Rubix",
        pseudo: "GalashBolomPolom",
        tag: "GBP",
        idLol: "BCQ4VH1TIuzsCI0r5rf2C2FonH_WILoV4_KHKe74-pxHMbZ0",
        team: "Team 2",
        twitch: "https://www.twitch.tv/arkheztv",
    },
    {
        id: 15,
        name: "Trabosx",
        pseudo: "Trafalgar Law",
        tag: "4444",
        idLol: "3ANO134XAWw_FYO51bUnEX8dc9A9E-pPQ3Jqz5vjDAX1x19aFRBq2JBrnA",
        team: "Team 4",
        twitch: "https://www.twitch.tv/arkheztv",
    },
    {
        id: 14,
        name: "Axelx",
        pseudo: "LaTekilaa",
        tag: "3265",
        idLol: "zWMz5oi3XnWgt4c5Q8yH7hMrNcdiqh4oGrWoeofVxF3DcL8Vom0er3cB0A",
        team: "Team 1",
        twitch: "https://www.twitch.tv/arkheztv",
    },
    {
        id: 13,
        name: "Arkhezx",
        pseudo: "Arkhez",
        tag: "EUW",
        idLol: "_r2HlqOEa5O447YmFlApvgITg5tsf-oL8qwSCnVdxCusdPg",
        team: "Team 3",
        twitch: "",
    },
    {
        id: 12,
        name: "Rubixx",
        pseudo: "GalashBolomPolom",
        tag: "GBP",
        idLol: "BCQ4VH1TIuzsCI0r5rf2C2FonH_WILoV4_KHKe74-pxHMbZ0",
        team: "Team 2",
        twitch: "",
    },
];
export default PLAYERS;