import player from './player.ts';

export const PLAYERS: player[] = [
    {
        id: 1,
        name: "Arkhez",
        pseudo: "TrasbosEnString",
        tag: "SLIP",
        idLol: "5GN8xTHsa6KUOiOfp7_AQiy91lnDkoWC_2ifVrZMrNi2tJyqOKKAExoU8A",
        team: "KingKong",
        twitch: "https://www.twitch.tv/arkheztv",
    },
    {
        id: 2,
        name: "Mariuto",
        pseudo: "Maroui",
        tag: "2206",
        idLol: "SXgh7CU0nq_xAOBLQmzg-vzGaRMVB5qgNJJTK-jNZ4CnjFGWHUpxiB2JSQ",
        team : "Nah I'd win",
        twitch: "",
    },
    {
        id: 3,
        name: "Viat",
        pseudo: "RIENATEGRAbdh",
        tag: "2433",
        idLol: "BPctBmtILojyZhrug7d32wTHrMKY7t1kVNzxIU7B6GdBB6-46JKsjzz9XA",
        team: "Team Paqueta",
        twitch: "https://www.twitch.tv/viattv",
    },
    {
        id: 4,
        name: "Raiden",
        pseudo: "Jeong Ji hoon",
        tag: "정지훈",
        idLol: "2ZbU229Baj9WaWPSIhzXksTzZkMXsMYHNcV4x_2YkmlCiCLbM3FzK668fg",
        team: "Nah I'd win",
        twitch: "https://www.twitch.tv/weezer___",
    },
    {
        id: 5,
        name: "Slash",
        pseudo: "김건부",
        tag: "KR3",
        idLol: "23DgXUZX37oIngx-FpQTyqg4EzkfVoIpEd1N0IVPFpLFaQsQ7qYM0c2QBg",
        team: "Team Paqueta",
        twitch: "",
    },
    {
        id: 6,
        name: "Rubix",
        pseudo: "NanikaHaruka",
        tag: "1234",
        idLol: "2qEJaTDEiYTBEmS4iw83P6XMdPSkmDMh_-1QfkA-yZHvKE_EfL4rb44bdw",
        team: "KingKong",
        twitch: "",
    },
    {
        id: 7,
        name: "Mastos",
        pseudo: "MALTY 2BZ",
        tag: "NCNC",
        idLol: "23DgXUZX37oIngx-FpQTyqg4EzkfVoIpEd1N0IVPFpLFaQsQ7qYM0c2QBg",
        team: "Don D. Gaetan",
        twitch: "https://www.twitch.tv/flyknit_",
    },
    {
        id: 8,
        name: "Axel",
        pseudo: "La4emeWave",
        tag: "2004",
        idLol: "ti6jwSbReBV7bJ8TwxbFUNftoqMv5LF_3gBa-vKSTKHp8p-z9YiUFGhRYQ",
        team: "Don D. Gaetan",
        twitch: "",
    },
];
export default PLAYERS;